# Application Configuration

server:
  port: 9091

# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  application:
    name: exchange-rate-service

  # ===============================
  # LOGS CREATION DB
  # ===============================
logging:
  level:
    io:
      r2dbc: debug
