# Application Configuration

server:
  port: 9091

# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  application:
    name: exchange-rate-service

  # ===============================
  # LOGS CREATION DB
  # ===============================
logging:
  level:
    io:
      r2dbc: debug
  # ===============================
  # API DOCUMENTATION
  # ===============================
springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui

  # ===============================
  # JWT CONFIGURATION
  # ===============================
security:
  jwt:
    id: challengeJWT
    token:
      secret-key: trtlG3JK5ámáwFFgsNPhqzjqW
      # 1 hour : 60 minutes * 60 seconds * 1000 m. seconds => 3600000
      expire-length: 3600000 # test 1 minute => 60000

cors-origin:
  path:
    web-app: http://localhost:4200/