create table tbl_currency
(id varchar(3) not null,
 description varchar(255),
 status boolean not null,
 creation_date timestamp not null,
 creation_user varchar(255) not null,
 modification_date timestamp null,
 modification_user varchar(255) null,
 primary key (id));

create table tbl_exchange_rate
(id bigint generated by default as identity,
 exchange_rate double,
 currency_id_from varchar(3),
 currency_id_to varchar(3),
 division boolean not null,
 status boolean not null,
 creation_date timestamp not null,
 creation_user varchar(255) not null,
 modification_date timestamp,
 modification_user varchar(255),
 primary key (id));

alter table tbl_exchange_rate add constraint uk_currency_from_to unique (currency_id_from, currency_id_to);
alter table tbl_exchange_rate add constraint fk_exchange_rate_currency_from foreign key (currency_id_from) references tbl_currency(id);
alter table tbl_exchange_rate add constraint fk_exchange_rate_currency_to foreign key (currency_id_to) references tbl_currency(id);

INSERT INTO tbl_currency (id, description, status,creation_user,creation_date)
VALUES ('USD','Dólar Estadounidense',true,'admin','2021-01-06');

INSERT INTO tbl_currency (id, description, status,creation_user,creation_date)
VALUES ('PEN','Sol Peruano',true,'admin','2021-01-06');

INSERT INTO tbl_exchange_rate (id, currency_id_from,currency_id_to,exchange_rate,division, status,creation_user,creation_date)
VALUES (1,'USD','PEN',4.01,false,true,'admin','2021-01-06');
INSERT INTO tbl_exchange_rate (id, currency_id_from,currency_id_to,exchange_rate,division, status,creation_user,creation_date)
VALUES (2,'PEN','USD',4.01,true,true,'admin','2021-01-06');